hybsearch/hybsearch

.travis.yml, Dockerfile
This would bump the version up to 9 instead of leaving it at 8, but beyond that should be end-to-end identical.  We "need Debian stretch," according @hawkrives, so that is why we aren't using something _cool_ like Alpine or the base default.
=> Use Docker.io's Node 9-stretch image

Dockerfile
I'd rather start off on an LTS release than on a short-lifetime release.
Plus, there's nothing currently in the project that needs Node 9, and I can't think of anything that it added that we'd want badly.
And if there is something, it's a single character change to get it back.
😃
=> Switch to Node 8 LTS

.travis.yml, README.md
Closes #16
Now, if you do `docker run -p 8080:8080 -t hybsearch/hybsearch`, you will get the "latest" tag that we've made (tags will show up in the Releases page: https://github.com/hybsearch/hybsearch/releases). This is the "stable" release of our pipeline.
> For all of these tags, when you want to update the image from the internet, you'll need to do this:
> ```
> docker pull hybsearch/hybsearch:$tag
> ```
We also have a tag for each branch, named after the branch (so, this branch is `hybsearch/hybsearch:auto-build-travis`); a tag for each git tag, named after the tag; and a tag named HEAD, which just tracks the tip of the `master` branch.
=> Automatically push new Docker tags from each branch

scripts/server.js
This prevents a server crash, but might result in one section of code never being called.  Not sure.  Best to have it in both places, in my opinion.
=> Only disconnect the child if the child is connected

lib/ent.js
Realized that Ent was sharing a global array… I've now removed that.
And, because I added tests for ent earlier this week, I'm fairly sure that this doesn't break anything!
=> Remove global shared mutable state from ent.js

electron/graph.js, electron/index.html, electron/run.js, lib/worker.js
I've completed adding the Ent search and parsing the newick tree as two new steps in the pipeline. I've also finished the `returnData` method so that the server can send data back to the client at multiple points and the client handles that. 
The app will now draw the tree immediately with no monophyly data yet. Once the ent is complete, it will redraw the graph with colors. 
I've opened this PR in case someone else is blocked on this. I've taken some shortcuts that I'd like to find better solutions for. Specifically I've realized that the `ent.strictSearch` function actually modifies the given newick tree, adding in data that is needed to correct mark the red nodes. My solution for now is resending the modified newick tree once the ent search is complete.
=> Ent in pipeline

electron/graph.js, electron/index.css, vendor/d3.phylogram.js
This fixes #42 by refactoring what clicking does. The old code was throwing an error because it was attempting to get input from an html input field that no longer exist.
The new behavior accepts clicks on any leaf node, and will pop up an alert telling you its pair. It will also set all other nodes except for the pair to opacity 0.2 so that it is visually easy to find the pair. Clicking again will reset everything to opacity 1 (clicking on a blue dot will also set opacity to 1). 
I would personally prefer to chuck the alert and just have it toggle the opacity, but I'm keeping it for now in case the biologists' use case is more about just getting the number than seeing it in the tree.
=> Clicking a node highlights its nonmonophylic pair

bin/fasta-to-nexus.js
Not necessarily the best of the options, but this does actually work pretty well.
I'd prefer us to use something like `which` to find it, but this solves the immediate problem on `master`.
Closes #56.
=> Point fasta-to-nexus to /usr/local/bin/seqmagick

.dockerignore, .gitignore, .ignore
I symlinked them both to the new `.ignore` file.
For our case, they should have the same content, so it makes sense to make them be the same file.
=> Centralize the .gitignore and .dockerignore files

.circleci/config.yml
we should have been doing this already
this allows circle to build and upload app binaries when we push a new tag
=> Enable building the app on tag pushes

server/docker-compose.yml
This is a one-to-one representation of what we run on thing3, and will make my life easier when I want to deploy on thing3.
I suppose you can just build that specific tag locally (`docker.io/hybsearch/hybsearch:HEAD`) as your development and run this locally, too.  (But it'll yell about port permissions, probably, lol)
=> Include a docker-compose.yml file

LICENSE
We have MIT license selected in `package.json`, but we don't actually have that anywhere else in the codebase.
This PR adds the MIT license, and directs the copyright to `The Hybsearch Team <hybsearch@stolaf.edu>`
=> Add the missing LICENSE file

.gitignore, electron/package-lock.json, electron/package.json, server/package-lock.json, server/package.json
Split out from #73 
- Renames the packages to remove the scope; it was pointless, and a few things wound up creating accidentally nested folders because of the slash
- Added a comment about why we ignore `dist/`
- Reduces the number of generated files, from `dmg(osx)`/`zip(osx)`/`exe(win)`/`snap(linux)`/`appimage(linux)` to just `zip(osx)`/`exe(win)`/`.tar.gz(linux)` – also the .dmg/.appimage weren't even being created right, so this reduces the number of errors logged, as well
=> Clean up the electron-builder config

.prettierignore, electron/package.json, package.json, server/package.json
This doesn't actually have any changes to the formatting.
- Uses the `.prettierignore` file to show that we're actually just ignoring these files
- Uses `^` notation when depending on `prettier`, to match all our other deps
- Renames `npm run prettier` to `npm run prettify` to allow future use cases (for instance, `yarn` lets you run any installed binary with `yarn $binary`, which I've found myself doing several times now.)
Split out from #73
=> Tweak the Prettier config a bit

electron/index.css, electron/index.html, electron/run.js, electron/ui.js, server/Dockerfile, server/lib/prune-newick.js, server/package-lock.json, server/package.json, server/pipeline/cache.js, server/pipeline/hyb-pipeline, server/pipeline/worker.js, server/server.js
closes #74 
I don't even know what all to put here right now
This redesigns the entire pipeline structure around a declarative set of `{input, transform, output}` tuples that facilitate the automatic caching of each step's output
- You will get an array of inputs and you are expected to return an array of outputs
- The order of the `input` array is the order you will get your arguments
- The order of the `output` array is matched with the order of the returned array
- The colons serve the purpose of indicating what progress dot to fill out – everything after the colon is stripped while searching for a progress dot
- don't forget that you can specify multiple inputs and multiple outputs, and also that you can have two inputs and only generate one output
- if you need to send updated data …
=> Cache the pipeline

server/Dockerfile
While I extol the virtues of multiarch builds, our app primarily targets amd64 devices, and I'm pretty sure we can only build on amd64 infrastructure.
As such, we should specify that in our Dockerfile.  This prevents outages like what happened with nodejs/docker-node#675, because instead of having to deal with issues such as amd64 images getting lost out of the manifest on Docker Hub, we just use whichever version is available for our specific architecture, and those only have one architecture in their manifest.  This issue was the result of a race condition: as soon as an arcane architecture finished building, the new docker image would get pushed, and then the Docker Hub manifests would get updated to only include that new architecture.
This commit switches to a side repository that …
=> Declaratively specify that we would like to use amd64 node images

electron/package.json, server/Dockerfile
npm did this by itself, and I'd rather not have this be unstaged and floating around... so, yeah.  I can't think of any reason (besides the extra SLoC induced by formatting it this way) to not do this.
Currently red in CI because of https://github.com/nodejs/docker-node/issues/675.  Will kick off the rebuild once that tag is present upstream.
Blocked by #83. (Safe to close #83 if this PR gets merged instead.)
=> Reformat electron/package.json

electron/index.html, electron/run.js, electron/ui.js, server/pipeline/lib.js, server/pipeline/pipelines/index.js, server/pipeline/pipelines/parse-newick.js, server/pipeline/pipelines/search.js, server/pipeline/worker.js
With this PR, the server can give you the list of supported pipelines.
This will allow us to support both the BEAST and the MrBayes pipelines while we investigate BEAST.
The loading dots are now dynamically provided by the selected pipeline, as well.
=> List pipelines dynamically from the server

.circleci/config.yml, electron/package.json
This lets the app building take place in parallel, which lets the average overall build time of 9m43s drop to 7m16s.
I think. Probably.
If it gets really slow, we can always revert it and go back to the single build step.
=> Split app building step

electron/index.css, electron/package-lock.json, electron/package.json, electron/run.js
It lets them look like this, with the units changing from "ms" always to "seconds" and even "minutes".
=> Format the step durations

server/Dockerfile
This shouldn't have too much of an impact on the overall Docker image size besides adding a teensy layer.  I don't think we have to copy any libraries or stuff over, because JML is pretty much standalone.
Part of #99.
=> Add JML binaries to Docker image

electron/index.html, electron/run.js, server/lib/prune-newick.js
The new algorithm as requested by Steve is:
_A sequence is removed if it is more than X% different from a majority of the other sequences, or if its length is less than Y_
We had talked about `X` being 50% but I ended up finding that 20% works better. And the cut off Y is a constant set at 300 currently. 
Here is a screenshot from running `pseudemyscytbplushnfal.fasta`
And from running `trio171seqshortaln.fasta`
I'd like to get this merged soon so that the biologists can run some tests and verify these constants.
=> New Algorithm for Pruning Outliers

package-lock.json, package.json
This release adds @OmarShehata's new outlier pruning algorithm from #104.
Edit: draft of the email…
---
Hey y'all,
–––
First off, Omar's finished his new outlier pruning algorithm:
> The new algorithm as requested by Steve is:
> 
> > A sequence is removed if it is more than X% different from a majority of the other sequences, or if its length is less than Y
> 
> We had talked about X being 50% but I ended up finding that 20% works better. And the cut off Y is a constant set at 300 currently.
So that's a thing! 👏👏👏
–––
Second, Kris and I finished the "mbnb" pipeline we were talking about in the Beta12 email last night.
What it does is to align the sequences, as usual, but then we run those aligned sequences through MrBayes to get our consensus tree, which we then send through Ent to find …
=> Release v4.0.0, beta 14

server/formats/__tests__/__snapshots__/fasta-to-beast.test.js.snap, server/formats/template.xml
Closes #112 
For now, we're going to go with 1M iterations. Later one, especially once we've parallelized this, we may look at increasing it to see what effects that has, but that's in the future.
=> Shrink beast iterations to 1M

electron/index.css
I think it looks much nicer
| Before |
| --- |
| <img width="450" alt="screen shot 2018-04-11 at 5 25 25 pm" src="https://user-images.githubusercontent.com/464441/38646373-56ced5c6-3dad-11e8-8b34-0ff721f07d14.png"> |
| After |
| <img width="450" alt="screen shot 2018-04-11 at 5 25 28 pm" src="https://user-images.githubusercontent.com/464441/38646379-58a29f36-3dad-11e8-8735-b381863a5dea.png"> |
=> use grid layout on the progress bar

server/formats/__tests__/__snapshots__/fasta-to-beast.test.js.snap, server/formats/template.xml
Reverts hybsearch/hybsearch#125
With ploidy=0.5 and this set to 1M:
With just ploidy=0.5:
I think that we should revert this until later, since we're fairly comfortable with the 10M output and that's pretty significantly different when we go to 1M.
---
edit: fixed accidentally attaching the same screenshot twice
edit 2: fixed order of screenshots
=> Revert "Shrink beast iterations to 1M"

electron/graph.js, electron/index.css, electron/index.html, electron/lib/html-table.js, electron/run.js, electron/ui.js
- Moves the nonmonophyly block below the graph, and turns it into a table (closes #114)
- Hides the Newick Tree input block while the pipeline is running (closes #113)
- Turns the "omitted sequences" block into a single-column table (just so it matches the others; the single column is called "node")
- Fixes a bug where the JML results table would grow a `__highlight` column (which is not useful)
- Disables the logging of every leaf graph node to the electron console
- Some minor code cleanup
before | after
--- | ---
=> Shuffle UI blocks around

server/docker-compose.yml
This will more explicitly define what we want, which is for pipeline caches to be persistent across runs.
I do this by adding two volumes.  Note that these files will not be accessible on the docker host side, as they shouldn't need to be.  Instead, we just just use Docker volumes.  If you need to get data out of this container, it's possible to do `--volumes-from` with a busybox container and then do a bridge mount.  But we don't need that.
=> Add pipeline caches to the docker-compose file

server/Dockerfile
We had it in there so that the wheel building step would pass, but since we don't use wheels to distribute our packages we don't care if the wheels build or not.
Wheels are a binary distribution format for Python packages, and I have yet to figure out how to ask Python to not generate them. Since we don't need to distribute the python package that we're building, we can ignore the fact that the wheels fail to build.
If the build failures mattered, `pip install` would exit with a non-0 status code, so this shouldn't affect our future stability.
=> Remove the pip upgrade step from Dockerfile

electron/ui.js, server/lib/get-files.js, server/package-lock.json, server/package.json, server/pipeline/worker.js, server/server.js
(@rye has been bugging me to do this for a while)
This lets the non-live bits of the app, like getting the list of pipelines, happen over a normal HTTP connection, instead of sending a message and waiting for a keyed response.
```js
socket.on('message', msg => {
let payload = JSON.parse(msg)
if (payload.type === 'get-pipelines') {
doThings(payload.pipelines)
}
})
socket.send('get-pipelines')
```
can become
```js
fetchJson(`${server}/pipelines`).then(doThings)
```
It should make for a much cleaner separation between the pipelines (which will stay on sockets) and the rest of the app.
@OmarShehata / @mollysrour – this probably doesn't change much for you, since you have been mainly working with pipeline data.
<details><summary>EDIT: removed this part from the PR</summary>
This also moves our …
=> Add REST endpoints to allow us to not use websockets for everything

server/docker-compose.yml
This enables the extended volumes syntax.  And prevents clients from using the stupid old syntax.
=> Declare 3.2 as the version on docker-compose.yml

server/Dockerfile
This should be harmless one way or the other, and immediately closes #145.
Older clients get a different error due to complete protocol mismatch, as we completely broke the old way of talking to the server in favor of a much better way.
=> Add run step for mkdir data/ in the build

package-lock.json, package.json, server/ent/__tests__/more-ent.test.js, server/formats/fasta/__tests__/__snapshots__/keep-identifiers.test.js.snap, server/formats/fasta/__tests__/keep-identifiers.test.js, server/formats/fasta/index.js, server/formats/fasta/keep-identifiers.js, server/formats/index.js, server/pipeline/pipelines/mbnb.js
Currently, we pass the filtered dataset into JML, without the nonmonophyletic sequences.
With this change, we give JML the entire dataset.
=> Run JML on the entire aligned FASTA dataset

server/Dockerfile
I am no longer locking versions down, though I could if necessary.
We'll use the `stretch` variant for now.  Eventually I'll have a way to tag as a specific version.
This should (help) fix broken builds on #170.
=> Fix broken JML build step

server/newick/hyb-newick-pretty, server/newick/printer.js
`/server/newick/hyb-newick-pretty kino.tree` will output a formatted tree to the terminal.
May be useful if you need to look at a Newick tree.
=> add an ASCII-art newick-tree-printer library/binary

electron/run.js
it was never unhidden otherwise
=> un-hide the tree when loading a json tree

electron/ui.js
Every time you changed servers, the list of files would get appended.
=> Fix a bug where the list of files would double in length

electron/index.css, electron/index.html, electron/run.js, electron/ui.js, server/formats/fasta-to-beast.js, server/formats/template.xml, server/lib/prune-newick.js, server/pipeline/cache.js, server/pipeline/pipelines/beast.js, server/pipeline/pipelines/index.js, server/pipeline/pipelines/mbnb-legacy.js, server/pipeline/pipelines/mbnb.js, server/pipeline/pipelines/parse-newick.js, server/pipeline/pipelines/search.js, server/pipeline/worker.js, server/server.js
This handles:
- specifying options in the pipeline
- rendering options in the UI
- passing options to the transform() functions, so that they can be passed to the actual functions
@OmarShehata, are the changes to `prune-newick` in https://github.com/hybsearch/hybsearch/pull/203/commits/7c6b3bf8646139a8ba486676262310db0be75162 correct for what we want to change, or do we need to change another field?
~~I should probably add one for BEAST repetitions, too.~~ Done as of 77bc599.
<details><summary>This also restructures the cache once more</summary>
it's now
```
/tmp/hybsearch/$combinedDataAndOptionsHash/$slashEscapedStepName
```
instead of
```
/tmp/hybsearch/$slashEscapedPipelineName/$dataHash/$slashEscapedStepName
```
</details>
---
~~I just realized that I forgot to actually send the …
=> Pass options to pipeline

electron/index.css, electron/index.html, electron/package-lock.json, electron/package.json, electron/run.js, electron/ui.js, server/job.js, server/lib/trim-message.js, server/package-lock.json, server/package.json, server/pipeline/cache.js, server/server.js
This PR separates the client connections from the running worker processes, allowing us several useful features:
- You can now close the client app, and the worker will continue running
- You can now "follow" an existing job, which will send you all of the events just like they're sent to the original client
- You can now cancel (or restart cancelled) jobs
=> Add job resumption support

electron/index.html, electron/run.js, server/lib/__tests__/__snapshots__/find-significant-nonmonophyly-test.js.snap, server/lib/__tests__/find-significant-nonmonophyly-test.js, server/lib/find-significant-nonmonophyly.js, server/pipeline/pipelines/mbnb.js, server/wrappers/jml/__tests__/__snapshots__/highlight.test.js.snap, server/wrappers/jml/__tests__/highlight.test.js, server/wrappers/jml/highlight.js, server/wrappers/jml/index.js
Closes #165 
- <details><summary>Removes the 'Sp Comparison' column from JML's Results table, since it's duplicated in the seq1/seq2 columns</summary>
</details>
- Moves "significant result" highlighting (p-value < 0.05) to the server
- Extracts any JML result row that (1) is highlighted and (2) includes some item from the Ent nonmonophyly list of accession numbers
=> Highlight significant nonmonophyly in a separate results box

server/lib/prune-newick.js, server/pipeline/pipelines/mbnb.js
@OmarShehata:
> The other one should be at a constant 0.5. That's my bad. It's 0.5 because we're saying if you're differnt from the majority, you're an outlier
>
> what is interesting is how different a given _gene_ sequence is
>
> That's why I was confusing how you were reporting those numbers for each species. because diff proportion is comparison value, not an absolute value
>
> …like, pairwise comparison
>
> This will be invaluable for researchers to see when something goes wrong, but most of the time will be just noise
=> Set outlierRemovalPercentage to apply to the proper spot

server/ent/ent.js, server/lib/get-leaf-nodes.js
- Makes use of `_.countBy` and `_.groupBy` instead of writing iterative loops
- Removes `debug` calls from `recursiveSearch`
- Uses `getLeafNodes` to power `findIndividualsOfSpecies` and `getAllIndividuals`
I'd like to merge this and continue other cleanups in future PRs, or else I'll get carried away like I usually do.
=> Starting some Ent cleanups

electron/index.css, electron/run.js
This speeds up the UI when JML decides to spit out ~50mb of text.
=> Delay creating the result blocks until the button is clicked

.circleci/config.yml
It consistently takes 3+ minutes to build, while macOS and Windows are both around 2min/2.5min.
That's my main reason, followed by the fact that none of us use a Linux GUI, and AFAIK it's never even been tested.
EDIT: With this, combined with the pipeline test changes in #211, we drop from around ~13m to run on Circle to only ~5m!
=> Remove linux build from CI

server/ent/ent.js
- Reduces indentation by switching loops to early-exits
- Switches a few loops to Array#filter/map instead of iteration
I highly recommend asking GitHub to hide the whitespace changes when reviewing: https://github.com/hybsearch/hybsearch/pull/228/files?w=1
=> More Ent cleanups

electron/package-lock.json, electron/package.json
This allows a number of dependencies to update, including cryptiles which had a CWE-331 vulnerability.
=> Update spectron to 4.0.0
