.dockerignore
Dockerfile
README.md

```shell
$ docker pull hawkrives/hybsearch
$ docker run -it hawkrives/hybsearch bash /hybsearch/scripts/compare-ent.sh /hybsearch/data/emydura-short.gb
```

Add a Docker container for easy running

---

.travis.yml

I love it when I can combine several previous things I've done to solve a new thing with minimal work.

Fix travis builds by using the docker container

---

README.md

point it to hybsearch/hybsearch instead of my old repo

update readme build badge

---

scripts/server.js

Yes, do that.  Note that this doesn't ensure full compliance with the question set forth in #17... but it's a start.

Server: Disconnect Child If WebSocket is closed

---

hamdis/hamming-distance.js

Changed code to account for hyphens

account for hyphens in hamming distance comparison function

---

electron/index.css

Updated css to read distance text

---

bin/clustal.js
bin/fasta-to-nexus.js
bin/mrbayes.js
bin/seq-gen.js

Use `which` to find executable binaries

---

.circleci/config.yml
electron/__tests__/app.test.js
electron/package-lock.json
electron/package.json

This just adds one test: it makes sure that the app launches successfully.
Yay.

Add Spectron for (very basic) Electron app tests

---

electron/graph.js

… fixes a bug I introduced, too. oops.
Split out from #73

Centralize #phylogram clearing

---

package-lock.json
package.json

Includes #76, #75, #74, #72, etc
I think that CI will automatically make the release for us when it attaches the build artifacts, so I'm just going to let it run.

v4.0.0-beta.8

---

server/Dockerfile
server/requirements.txt

Seems like this solves the problem identified in #84.
Results in a passing build with no error messages locally.
Closes #84.

Upgrade pip when building Docker image

---

.circleci/config.yml
electron/package-lock.json
electron/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json

This should resolve my problems from the previous beta attempt.

Release v4.0.0, beta 10

---

package-lock.json
package.json

Release v4.0.0, beta 11

---

package-lock.json
package.json

This will be our big fancy first-pass-at-JML release! 🎉

Release v4.0.0, beta 12

---

package-lock.json
package.json

This release will add the Mr. Bayes 'n' Beast (MB'n'B) pipeline that @hawkrives added in #103.

Release v4.0.0, beta 13

---

package-lock.json
package.json

This includes my µ-fix to the UI so that JML stuff actually gets rendered.

Release v4.0.0, beta 15

---

server/formats/__tests__/__snapshots__/fasta-to-beast.test.js.snap
server/formats/template.xml

this does something about switching BEAST's interpretation of DNA to fit mitochondrial DNA?
Closes #118

Set ploidy="0.5" on BEAST input file

---

package-lock.json
package.json

Includes:
- #129 (fixes some UI issues)
- #127 (makes the progress bar nicer)
- #126 (set `ploidy="0.5"` for BEAST to tell it to interpret the DNA as mitochondrial DNA)
**edit:** tag build: https://circleci.com/workflow-run/6ba8e0be-6cf7-40cb-9859-a94a4cc24a33

Release v4.0.0-beta.16

---

package.json

Double-quote the package.json globs for Windows

---

.prettierignore
electron/package-lock.json
electron/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json

The most notable change here is that I added two optional dependencies for `ws`, our WebSocket server, which its readme claims will speed it up.
Other than that, no surprises, and no formatting changes.

Update our JS dependencies

---

server/wrappers/jml/__tests__/__snapshots__/ctl.test.js.snap
server/wrappers/jml/ctl.js

Not sure what this does, but it should work?

Use a locusrate of 1.0

---

package-lock.json
package.json

This PR bumps the version to beta 17.
[Tag Workflow](https://circleci.com/workflow-run/fb93ad51-263e-4b3e-ad85-f8a13c814916)
[Branch Workflow](https://circleci.com/workflow-run/0aa6f5af-582b-4058-8c3f-f156911bc79d)

Release v4.0.0, beta.17

---

package-lock.json
package.json

yee-hah
because of #156 
tag build: https://circleci.com/workflow-run/fc9a87af-d57f-4f04-a712-a3945a26da83
commit: https://circleci.com/workflow-run/e7e1565c-24fb-4b36-8b8b-85980c6ac169

release 4.0.0-beta.18

---

package-lock.json
package.json

Includes #158, a hotfix for #156

Release v4.0.0 beta.19

---

server/formats/genbank-to-fasta.js

Closes #36 
Should fix some wierdness with some input files.

exclude entries with " sp." at the end of their organism name

---

package-lock.json
package.json

Release 4.0.0, beta 24

---

server/formats/fasta/keep-identifiers.js
server/formats/fasta/remove-identifiers.js
server/package.json

Just ~~two~~ three little code cleanups.

Code cleanups

---

package-lock.json
package.json

Includes #194 (json newick trees), #192 (genbank parsing), #185 (sped up Ent searches), #188 (felidae), and #186 (deduplicated test data files).
Tag build: https://circleci.com/workflow-run/04337e20-5486-4599-aed3-087b8679c4c8

Release v4.0.0 (beta 26)

---

package-lock.json
package.json

Includes #197 and #198, which together revise the Ent nonmonophyly filtering algorithm.

Release v4.0.0 (beta 27)

---

electron/index.css
electron/package-lock.json
electron/package.json
electron/run.js

Closes #132 
This PR allows you to view the results of each step by simply clicking on the step's icon.
You can also copy the original data to your clipboard with a handy Copy button.
(I added the Copy to Clipboard button late in the process.)

Allow viewing the results of each step

---

package-lock.json
package.json

Includes: 
- #200 (client-side tree hamming diff values)
- #202 (bugfix about duplicating dropdown entries)
- #203 (allow passing options to the pipelines)
- #204 (highlight significant nonmonophyly in a separate box)
- #205 (allow clients to detach and follow other jobs)
- #206 (allow viewing the results of each step)
- #208 (add menus to the app and allow multiple windows)
- #210 (allow setting the outlierPercentage as an option)
- #211 & #213 (update Ent filtering)
- #207 & #212 (some internal cleanups and dep updates)

Release v4.0.0, Release Candidate 1

---

server/formats/fasta/__tests__/__snapshots__/hash-names.test.js.snap
server/formats/fasta/__tests__/hash-names.test.js

Update hash-names tests

---

.circleci/config.yml
server/package-lock.json
server/package.json
server/pipeline/hyb-pipeline
server/pipeline/pipelines/mbnb-legacy.js

This drops the number of iterations when we run Beast on CircleCI to only 10,000 – this is OK because we're just making sure that the pipeline doesn't throw errors.

Faster beast tests on Circle

---

package-lock.json
package.json

Includes:
- #214 (update hash-names tests)
- #217 (Speed up BEAST tests on CircleCI) [from ~2.5m to ~50s]
- #216 (Delay creating the result dialogs until the button is clicked)

Release v4.0.0, Release Candidate ②

---

electron/run.js

fix get-ip on windows

---

server/formats/__tests__/fix-fasta-source.test.js
server/formats/fix-fasta-source.js

We already remove them from Genbank files

Remove "sp." entries from FASTA source files

---

server/lib/prune-newick.js

Starting work on some code cleanups in pruneNewick.
I'll make more branches off of this one.

Initial pruneNewick cleanups

---

electron/package-lock.json
electron/package.json

This did successfully open a window locally.

Update electron to 3.0.3

---

server/package-lock.json
server/package.json

This is a security update, and did run fine locally.

Update utf-8-validate to version 5.0.1

---

server/package-lock.json
server/package.json

This is a security update, and did run fine locally.

Update bufferutil to version 4.0.0

---

server/pipeline/pipelines/mbnb.js
server/ui/ui.js
server/wrappers/jml/__tests__/__snapshots__/ctl.test.js.snap
server/wrappers/jml/ctl.js
server/wrappers/jml/index.js
server/wrappers/mrbayes/index.js

This takes the simple approach of just exposing a `<textarea>` and combining the contents back into the config file on the backend.
Closes #241

Expose JML and MrBayes config to the UI
